### ISSUE TITLE
Question about single ion term

### ISSUE THREAD

**Issue by chengyangXu** [nafiserb/ESpinS#2]
The project is helpful for my study, yet I am confused about single ion term described in your tutorial. Is that more reasonable that the single ion term is expressed by Δ(Siz)^2 because the magnetic anisotrpy decscribes the favouring spin orientation but not the z component of spin?  And is the hamiltonian in your code is the same as what you written in the tutorial?

**Comment by nafiserb** [comment]
You are right. It was a mistake inside the user guide (tutorial). I corrected the single ion term inside the user guide.
The Hamiltonian inside the code is correct and uses Δ(Siz)^2 for the single ion.
