### ISSUE TITLE
strange output in fef3_vispin*.dat

### ISSUE THREAD

**Issue by zhl-95** [nafiserb/ESpinS#4]
the script vispin.x always come out with strange data that inconsistent with seedname_sconfig.dat.

This problem can also appear in example03. In line 142 of fef3_vispin001.dat
`Fe   0.20650000E+02  0.12906250E+02  0.12906250E+02  0.43712300E+00  0.00000000E+00  0.60134700-153`

**Comment by nafiserb** [comment]
we are working on this issue.

**Comment by nafiserb** [comment]
Now vispin.x work correctly.  Would you please tell us if still there is a problem in vispin.x?
