### ISSUE TITLE
What are the values of spins Si and Sj and Magnetic moment

### ISSUE THREAD

**Issue by Abhijit2052** [nafiserb/ESpinS#9]
First of all I would like to thank for the Espins package as I am new to this package i want to know are the spin values Si and Sj normalised to 1? and for all the systems do i have to take the magnetic moment as 1 in the input1 file?
Thank you

**Comment by nafiserb** [comment]
You can use whatever value for Si and Sj. In the block atoms_frac or  atoms_cart block, you can specify the magnetic moments for Si. The code doesn't normalize them to 1 during MC simulations. But I recommend setting the magnetic moments to 1.

**Comment by Abhijit2052** [comment]
Thanks for the response.
